version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustruct
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gosec
    - inamedparam
    - lll
    - mnd
    - musttag
    - nestif
    - nlreturn
    - noctx
    - nonamedreturns
    - noinlineerr
    - paralleltest
    - promlinter
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 170
      statements: 120
    gocognit:
      min-complexity: 35
    goconst:
      min-len: 8
      min-occurrences: 12
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 20
    gomoddirectives:
      replace-local: true
    govet:
      enable-all: true
      settings:
        printf:
          funcs:
            - Tracef
            - Infof
            - Warnf
            - Errorf
            - Fatalf
            - Criticalf
            - Panicf
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - forbidigo
          - forcetypeassert
          - mnd
        path: _test\.go
      - linters:
          - forbidigo
        path: nagflux.go
      - path: (.+)\.go$
        text: 'Magic number: 1\D '
      - path: (.+)\.go$
        text: 'Magic number: 2\D '
      - path: (.+)\.go$
        text: 'Magic number: 10\D '
      - path: (.+)\.go$
        text: 'Magic number: 100\D '
      - path: (.+)\.go$
        text: 'Magic number: 500\D '
      - path: (.+)\.go$
        text: 'fieldalignment:'
      - path: (.+)\.go$
        text: 'fmtappendf:'
      - path: (.+)\.go$
        text: 'minmax:'
      - path: (.+)_test\.go$
        text: 'stringsbuilder:'
      - path: (.+)_test\.go$
        text: 'concat-loop:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
